######################################################################
# Automatically generated by qmake (3.0) Fri Jul 22 23:45:45 2016
######################################################################

TEMPLATE = app
TARGET = worker
INCLUDEPATH += . Headers

# Input
HEADERS += Headers/worker.h
SOURCES += Sources/main.cpp Sources/worker.cpp
